name: Build, test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_repository:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

        # typescript-eslint needs all packages to be built
        # to check type-related linting rules
      - name: Check for linting errors
        run: yarn lint

      - name: Test API Client
        run: yarn test:api-client --coverage

      - name: check api-client coverage file
        id: api-coverage
        run: echo "exists=$((test -s packages/api-client/coverage/lcov.info && echo 'true') || echo 'false')" >> $GITHUB_OUTPUT

      - name: SonarCloud Scan api-client
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN_API_CLIENT }}
        with:
          projectBaseDir: packages/api-client
          args: >
            -Dsonar.organization=vuestorefront
            -Dsonar.projectKey=vuestorefront_magento2_api-client
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.coverage.exclusions=__tests__/**,*.config.js,src/index.ts,src/api-extractor-data.ts,**/types/**
            -Dsonar.cpd.exclusions=__tests__/**
